"""add status

Revision ID: 494314c5a20e
Revises: 1d7364509f47
Create Date: 2024-11-24 07:51:01.752626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '494314c5a20e'
down_revision: Union[str, None] = '1d7364509f47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_results', sa.Column('status', sa.String(length=50), default="running", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_results', 'status')
    # ### end Alembic commands ###
